language: python
python:
  - 3.4

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$PATH:$HOME/miniconda2/bin
  - export PYTHONPATH=$HOME/virtualenv/python3.4.6/lib/python3.4/site-packages/:$HOME/miniconda2/lib/python2.7/site-packages/
  - export LD_LIBRARY_PATH=$HOME/miniconda2/lib/python2.7/site-packages/rdkit/
  - conda update --yes -q conda
  - conda config --set always_yes true
  - conda config --set anaconda_upload no

# Install packages
install:
  - pip3 install --upgrade -r requirements.txt
  - conda install --use-local -c conda-forge rdkit

script: python -m pytest tests/test_methods.py
