package:
  name: analogs_finder
  version: "1.2.1"

about:
  home: https://github.com/danielSoler93/analogs_finder
  license: Apache
  license_file: LICENSE
  summary: Find analogs from query molecule and database

source:
  path: ../

build:
  script: python -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - python

  run:
    # Base dependencies
    - python
    - numpy
    - matplotlib
    - umap-learn
    - jinja2
    - scikit-learn
    - tqdm
    - mpld3
    - rdkit

test:
  imports:
    - analogs_finder
  source_files:
    - tests
  requires:
    - pytest
